# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1100, 600)
        self.graphicsView_2 = QtWidgets.QGraphicsView(parent=Form)
        self.graphicsView_2.setGeometry(QtCore.QRect(860, 130, 231, 192))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(parent=Form)
        self.graphicsView_3.setGeometry(QtCore.QRect(620, 390, 231, 192))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_4 = QtWidgets.QGraphicsView(parent=Form)
        self.graphicsView_4.setGeometry(QtCore.QRect(860, 390, 231, 192))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(860, 90, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Enigmatic Unicode")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(860, 350, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Enigmatic Unicode")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(620, 350, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Enigmatic Unicode")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Proteins"))
        self.label_4.setText(_translate("Form", "Carbohydrates"))
        self.label_5.setText(_translate("Form", "Fats"))
